// @ts-nocheck
'use client';
import{useEffect,useRef}from'react';import*as THREE from'three';import'./ColorBends.css';
const M=8;
const f=`#define MAX_COLORS 8
uniform vec2 uCanvas;uniform float uTime,uSpeed;uniform vec2 uRot;uniform int uColorCount;uniform vec3 uColors[MAX_COLORS];uniform int uTransparent;uniform float uScale,uFrequency,uWarpStrength;uniform vec2 uPointer;uniform float uMouseInfluence,uParallax,uNoise;uniform int uIterations;uniform float uIntensity,uBandWidth;varying vec2 vUv;
void main(){float t=uTime*uSpeed;vec2 p=vUv*2.-1.;p+=uPointer*uParallax*.1;vec2 rp=vec2(p.x*uRot.x-p.y*uRot.y,p.x*uRot.y+p.y*uRot.x);vec2 q=vec2(rp.x*(uCanvas.x/uCanvas.y),rp.y);q/=max(uScale,.0001);q/=.5+.2*dot(q,q);q+=.2*cos(t)-7.56;q+=(uPointer-rp)*uMouseInfluence*.2;for(int j=0;j<5;j++){if(j>=uIterations-1)break;vec2 rr=sin(1.5*(q.yx*uFrequency)+2.*cos(q*uFrequency));q+=(rr-q)*.15;}vec3 col=vec3(0);float a=1.;if(uColorCount>0){vec2 s=q;vec3 sumCol=vec3(0);float cover=0.;for(int i=0;i<MAX_COLORS;++i){if(i>=uColorCount)break;s-=.01;vec2 r=sin(1.5*(s.yx*uFrequency)+2.*cos(s*uFrequency));float m0=length(r+sin(5.*r.y*uFrequency-3.*t+float(i))/4.);float k=clamp(uWarpStrength,0.,1.);float km=pow(k,.3);float gain=1.+max(uWarpStrength-1.,0.);vec2 warped=s+(r-s)*k*gain;float m1=length(warped+sin(5.*warped.y*uFrequency-3.*t+float(i))/4.);float m=mix(m0,m1,km);float w=1.-exp(-uBandWidth/exp(uBandWidth*m));sumCol+=uColors[i]*w;cover=max(cover,w);}col=clamp(sumCol,0.,1.);a=uTransparent>0?cover:1.;}else{vec2 s=q;for(int k=0;k<3;++k){s-=.01;vec2 r=sin(1.5*(s.yx*uFrequency)+2.*cos(s*uFrequency));float m0=length(r+sin(5.*r.y*uFrequency-3.*t+float(k))/4.);float kb=clamp(uWarpStrength,0.,1.);float km=pow(kb,.3);float gain=1.+max(uWarpStrength-1.,0.);vec2 warped=s+(r-s)*kb*gain;float m1=length(warped+sin(5.*warped.y*uFrequency-3.*t+float(k))/4.);col[k]=1.-exp(-uBandWidth/exp(uBandWidth*mix(m0,m1,km)));}a=uTransparent>0?max(max(col.r,col.g),col.b):1.;}col*=uIntensity;if(uNoise>.0001){float n=fract(sin(dot(gl_FragCoord.xy+vec2(uTime),vec2(12.9898,78.233)))*43758.5453123);col+=(n-.5)*uNoise;col=clamp(col,0.,1.);}vec3 rgb=uTransparent>0?col*a:col;gl_FragColor=vec4(rgb,a);}`;
const v=`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,1.);}`;
type ColorBendsProps={className?:string;style?:React.CSSProperties;rotation?:number;speed?:number;colors?:string[];transparent?:boolean;autoRotate?:number;scale?:number;frequency?:number;warpStrength?:number;mouseInfluence?:number;parallax?:number;noise?:number;iterations?:number;intensity?:number;bandWidth?:number};
export default function ColorBends({className='',style,rotation=90,speed=.2,colors=[],transparent=true,autoRotate=0,scale=1,frequency=1,warpStrength=1,mouseInfluence=1,parallax=.5,noise=.15,iterations=1,intensity=1.5,bandWidth=6}:ColorBendsProps){const c=useRef(null),rr=useRef(null),raf=useRef(null),mr=useRef(null),ro=useRef(null),rot=useRef(rotation),ar=useRef(autoRotate),pt=useRef(new THREE.Vector2),pc=useRef(new THREE.Vector2);
useEffect(()=>{const e=c.current;if(!e)return;const s=new THREE.Scene(),cam=new THREE.OrthographicCamera(-1,1,1,-1,0,1),g=new THREE.PlaneGeometry(2,2),ca=Array.from({length:M},()=>new THREE.Vector3);const m=new THREE.ShaderMaterial({vertexShader:v,fragmentShader:f,uniforms:{uCanvas:{value:new THREE.Vector2(1,1)},uTime:{value:0},uSpeed:{value:speed},uRot:{value:new THREE.Vector2(1,0)},uColorCount:{value:0},uColors:{value:ca},uTransparent:{value:transparent?1:0},uScale:{value:scale},uFrequency:{value:frequency},uWarpStrength:{value:warpStrength},uPointer:{value:new THREE.Vector2},uMouseInfluence:{value:mouseInfluence},uParallax:{value:parallax},uNoise:{value:noise},uIterations:{value:iterations},uIntensity:{value:intensity},uBandWidth:{value:bandWidth}},premultipliedAlpha:true,transparent:true});mr.current=m;s.add(new THREE.Mesh(g,m));const r=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',alpha:true});rr.current=r;r.outputColorSpace=THREE.SRGBColorSpace;r.setPixelRatio(Math.min(devicePixelRatio||1,2));r.setClearColor(0,transparent?0:1);Object.assign(r.domElement.style,{width:'100%',height:'100%',display:'block'});e.appendChild(r.domElement);const clock=new THREE.Clock(),resize=()=>{const w=e.clientWidth||1,h=e.clientHeight||1;r.setSize(w,h,false);m.uniforms.uCanvas.value.set(w,h)};resize();if('ResizeObserver'in window){ro.current=new ResizeObserver(resize);ro.current.observe(e)}else addEventListener('resize',resize);const loop=()=>{const dt=clock.getDelta(),t=clock.elapsedTime;m.uniforms.uTime.value=t;const rad=((rot.current%360)+ar.current*t)*Math.PI/180;m.uniforms.uRot.value.set(Math.cos(rad),Math.sin(rad));pc.current.lerp(pt.current,Math.min(1,dt*8));m.uniforms.uPointer.value.copy(pc.current);r.render(s,cam);raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf.current);if(ro.current)ro.current.disconnect();else removeEventListener('resize',resize);g.dispose();m.dispose();r.dispose();r.forceContextLoss();r.domElement.remove()}},[bandWidth,frequency,intensity,iterations,mouseInfluence,noise,parallax,scale,speed,transparent,warpStrength]);
useEffect(()=>{const m=mr.current,r=rr.current;if(!m)return;rot.current=rotation;ar.current=autoRotate;Object.assign(m.uniforms.uSpeed,{value:speed});m.uniforms.uScale.value=scale;m.uniforms.uFrequency.value=frequency;m.uniforms.uWarpStrength.value=warpStrength;m.uniforms.uMouseInfluence.value=mouseInfluence;m.uniforms.uParallax.value=parallax;m.uniforms.uNoise.value=noise;m.uniforms.uIterations.value=iterations;m.uniforms.uIntensity.value=intensity;m.uniforms.uBandWidth.value=bandWidth;const arr=(colors||[]).filter(Boolean).slice(0,M).map(x=>new THREE.Color(x));for(let i=0;i<M;i++)i<arr.length?m.uniforms.uColors.value[i].set(arr[i].r,arr[i].g,arr[i].b):m.uniforms.uColors.value[i].set(0,0,0);m.uniforms.uColorCount.value=arr.length;m.uniforms.uTransparent.value=transparent?1:0;if(r)r.setClearColor(0,transparent?0:1)},[rotation,autoRotate,speed,scale,frequency,warpStrength,mouseInfluence,parallax,noise,iterations,intensity,bandWidth,colors,transparent]);
useEffect(()=>{const e=c.current;if(!e)return;const move=x=>{const b=e.getBoundingClientRect();pt.current.set((x.clientX-b.left)/(b.width||1)*2-1,-((x.clientY-b.top)/(b.height||1)*2-1))};e.addEventListener('pointermove',move);return()=>e.removeEventListener('pointermove',move)},[]);return <div ref={c} className={`color-bends-container ${className}`} style={style}/>}
