'use client';
import Image from 'next/image';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { type FormEvent, useState } from 'react';
import { db } from '@/lib/firebase';
import ColorBends from './components/ColorBends';
import Aurora from './components/Aurora';
import GradientBlinds from './components/GradientBlinds';

const WA = 'https://wa.me/5511999999999?text=Ol%C3%A1%2C%20quero%20criar%20meu%20site%20com%20a%20Alvenn.';
const solutions = [['Design premium','Uma estética exclusiva, construída para posicionar sua marca acima da média.'],['Experiência','Navegação intuitiva e envolvente em cada tela, do primeiro clique ao contato.'],['Conversão','Estratégia, hierarquia e chamadas pensadas para transformar visitas em oportunidades.'],['Performance','Carregamento rápido, código otimizado e a melhor experiência em qualquer dispositivo.']];
const steps = [['01','Briefing','Você responde algumas perguntas para entendermos seu negócio, público e objetivos.'],['02','Criação','Transformamos estratégia em uma experiência digital única, com acompanhamento próximo.'],['03','No ar','Após sua aprovação, publicamos tudo e sua nova presença começa a trabalhar por você.']];
const faqs = [['O site será personalizado?','Sim. Cada projeto é criado do zero para refletir a personalidade, o posicionamento e os objetivos da sua empresa.'],['Funciona no celular?','Perfeitamente. O site é responsivo e testado para entregar uma experiência impecável em celulares, tablets e computadores.'],['Posso pedir alterações?','Sim. Você acompanha o processo e pode solicitar ajustes nas etapas de revisão antes da publicação.'],['Preciso enviar os textos?','Não necessariamente. Podemos organizar e refinar sua mensagem a partir do briefing para que ela seja clara, estratégica e convincente.']];
const Arrow = () => <span aria-hidden="true">↗</span>;

export default function Home() {
 const [openFaq,setOpenFaq]=useState(0);
 const [loading,setLoading]=useState(false);
 const [feedback,setFeedback]=useState<{type:'success'|'error';message:string}|null>(null);
 const handleSubmit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const formData=new FormData(form);setLoading(true);setFeedback(null);try{await addDoc(collection(db,'leads'),{nome:String(formData.get('nome')??'').trim(),email:String(formData.get('email')??'').trim(),whatsapp:String(formData.get('whatsapp')??'').trim(),mensagem:String(formData.get('mensagem')??'').trim(),createdAt:serverTimestamp()});form.reset();setFeedback({type:'success',message:'Mensagem enviada com sucesso! Em breve entraremos em contato.'})}catch(error){console.error('Erro ao enviar formulário:',error);setFeedback({type:'error',message:'Não foi possível enviar sua mensagem. Tente novamente.'})}finally{setLoading(false)}};
 return <main>
  <header className="island"><a href="#inicio" className="brand" aria-label="Alvenn - início"><Image src="/alvenn-logo.png" width={34} height={34} alt="" priority/><span>alvenn.ai</span></a><nav aria-label="Navegação principal"><a href="#sobre">Sobre</a><a href="#solucao">Solução</a><a href="#processo">Processo</a><a href="#faq">FAQ</a></nav><a className="nav-cta" href="#contato">Iniciar projeto <Arrow/></a></header>
  <section id="inicio" className="hero section-dark"><div className="webgl-layer"><ColorBends colors={['#ff5c7a','#8a5cff','#00ffd1']} rotation={46} speed={0.6} scale={0.5} frequency={0.9} warpStrength={1} mouseInfluence={1} noise={0.15} parallax={0.5} iterations={1} intensity={1.5} bandWidth={6} transparent /></div><div className="hero-shade"/><div className="hero-content wrap"><span className="eyebrow light"><i/> DESIGN • ESTRATÉGIA • PERFORMANCE</span><h1>Sua marca merece uma <em>presença à altura.</em></h1><p>Sites estratégicos, sofisticados e construídos para transformar atenção em oportunidade.</p><a href="#contato" className="button button-light">Quero meu projeto <Arrow/></a></div><div className="scroll-note">Explore <span>↓</span></div></section>
  <section id="sobre" className="about section-light"><div className="wrap about-grid"><div><span className="eyebrow"><i/> QUEM ESTÁ POR TRÁS</span><div className="portrait-mark">A<span>JL</span></div></div><div><p className="lead">Prazer, eu sou <strong>Jean Lucas.</strong> Empreendedor, autodidata e apaixonado por tecnologia.</p><p className="body-copy">Fundei a Alvenn com um objetivo simples: criar experiências digitais que unam design, estratégia e performance para transformar a forma como empresas se apresentam no digital.</p><div className="signature">Jean Lucas <small>Fundador da Alvenn</small></div></div></div></section>
  <section id="solucao" className="solution section-dark"><div className="webgl-layer aurora"><Aurora colorStops={['#01061b','#0b42d2','#55aaff']} blend={0.55} amplitude={1.2} speed={0.55}/></div><div className="wrap solution-card"><span className="eyebrow"><i/> O QUE ENTREGAMOS</span><div className="solution-head"><h2>Muito além de um<br/><em>site bonito.</em></h2><p>Criamos um ativo digital que trabalha para construir percepção, comunicar valor e gerar novas oportunidades.</p></div><div className="feature-grid">{solutions.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section id="processo" className="process section-dark"><div className="webgl-layer blinds"><GradientBlinds gradientColors={['#02030a','#0638ba','#5ba9ff']} blindCount={10}/></div><div className="process-shade"/><div className="wrap process-content"><span className="eyebrow light"><i/> NOSSO PROCESSO</span><h2>Simples do início<br/><em>ao fim.</em></h2><div className="steps">{steps.map(([number,title,text])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
  <section className="offer section-light"><div className="wrap offer-grid"><div><span className="eyebrow"><i/> SUA NOVA PRESENÇA</span><h2>Uma presença digital feita para <em>impressionar.</em></h2><p>Do conceito à publicação, cuidamos de cada detalhe para sua empresa ser vista como merece.</p></div><div className="offer-card"><ul>{['Design exclusivo e alinhado à sua marca','Experiência responsiva em todos os dispositivos','Estrutura estratégica focada em conversão','Otimização de velocidade e SEO','Domínio, publicação e suporte especializado'].map(item=><li key={item}><span>✓</span>{item}</li>)}</ul><a href="#contato" className="button button-blue">Quero começar <Arrow/></a></div></div></section>
  <section id="faq" className="faq section-light"><div className="wrap faq-grid"><div><span className="eyebrow"><i/> PERGUNTAS FREQUENTES</span><h2>Antes de começar,<br/><em>tire suas dúvidas.</em></h2></div><div className="accordion">{faqs.map(([q,a],i)=><article className={openFaq===i?'open':''} key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} aria-expanded={openFaq===i}><span>{q}</span><b>{openFaq===i?'−':'+'}</b></button><div className="answer"><p>{a}</p></div></article>)}</div></div></section>
  <section id="contato" className="contact section-dark"><div className="contact-glow"/><div className="wrap contact-grid"><div><span className="eyebrow light"><i/> VAMOS CONVERSAR</span><h2>Sua empresa já existe.<br/>Agora faça ela ser <em>percebida.</em></h2><p>Conte um pouco sobre seu projeto. Em breve, entraremos em contato para dar o próximo passo.</p></div><form onSubmit={handleSubmit}><label>Nome<input name="nome" placeholder="Como podemos chamar você?" required/></label><label>E-mail<input name="email" type="email" placeholder="voce@empresa.com" required/></label><label>WhatsApp<input name="whatsapp" inputMode="tel" placeholder="(00) 00000-0000" required/></label><label>Mensagem<textarea name="mensagem" rows={3} placeholder="Conte brevemente sobre o seu projeto"/></label><button className="button button-light" type="submit" disabled={loading}>{loading?'Enviando...':'Criar meu projeto'} <Arrow/></button>{feedback&&<p role="status" aria-live="polite" style={{margin:'18px 0 0',color:feedback.type==='success'?'#8de8ae':'#ff9aa8',lineHeight:1.6}}>{feedback.message}</p>}</form></div></section>
  <footer><div className="wrap footer-top"><div><a href="#inicio" className="footer-brand"><Image src="/alvenn-logo.png" width={48} height={48} alt="Logo da Alvenn"/><span>alvenn.ai</span></a><p>Sites que unem design,<br/>estratégia e experiência.</p></div><div className="footer-links"><div><small>SOCIAL</small><a href="#">Instagram</a><a href={WA}>WhatsApp</a></div><div><small>LEGAL</small><a href="#">Política de Privacidade</a><a href="#">Termos de Uso</a></div></div></div><div className="wrap footer-bottom"><span>© 2026 Alvenn. Todos os direitos reservados.</span><span>Feito com intenção no Brasil.</span></div></footer>
  <a href={WA} className="whatsapp" aria-label="Falar com a Alvenn no WhatsApp" target="_blank" rel="noreferrer"><span>◔</span><b>WhatsApp</b></a>
 </main>
}
